### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by fickmj** [dialogflow/dialogflow-javascript-client#80]
After installing api-ai-javascript beta 21 i get the following errors when attempting ng serve or ng build:
![screenshot_031418_114553_am](https://user-images.githubusercontent.com/28792675/37417009-413301a6-277d-11e8-8be3-bd59423d8c9c.jpg)

**Comment by mboughaba** [comment]
Hi @fickmj 

Make sure to add `api-ai-javascript index.ts` to your tsconfig files include (`tsconfig.app.json` and `tsconfig.spec.json` )

```json
{
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts",
    "../node_modules/api-ai-javascript/index.ts",
    "./main.ts",
    "./polyfills.ts"
  ]
}
```

**Comment by joaovictortinoco** [comment]
Hi @mboughaba 

I faced this error after your suggestion: 

> ERROR in ./src/main.ts
Module build failed: Error: {PROJECT_PATH}/src/main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile ({PROJECT_PATH}/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then ({PROJECT_PATH}/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
ERROR in ./src/polyfills.ts
Module build failed: Error: {PROJECT_PATH}/src/polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/{PROJECT_PATH}/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then ({PROJECT_PATH}/node_modules/@ngtools/webpack/src/loader.js:467:39)

**Comment by mboughaba** [comment]
you need to add the missing files in your include.

The example I gave works with my setup 🤣 
you need to adapt the relative paths in the include array

so I suggest that you change it to:
```
{
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts",
    "../node_modules/api-ai-javascript/index.ts",
    "./src/main.ts",
    "./src/polyfills.ts"
  ]
}
```

**Comment by joaovictortinoco** [comment]
Got it! It's working and now it's fine. Thank you!

**Comment by fickmj** [comment]
Thanks for the help.  That worked!

**Comment by TudorIoanMarin** [comment]
I have the same problem compiling with angular-cli. I added the file in the include array in tsconfig.spec.json and I get this error. I tries adding it under files and under include. Relative file path is correct.

/node_modules/api-ai-javascript/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format

**Comment by smanjesh** [comment]
I did as suggested by @mboughaba, but I am now getting a new build error:
ERROR in No NgModule metadata found for 'AppModule'
I am running Angular CLI 6.0.1
Please help

**Comment by abhishekpoonia31** [comment]
Facing same error with Angular CLI 6

**Comment by jeroenouw** [comment]
Same here

**Comment by Intellinto** [comment]
@abhishekpoonia31 and @Juli15Boy did you find any fix for your issue? I am having the same problem

**Comment by dave-ramirez** [comment]
@jeroenouw great! is working for my!

**Comment by Zefearr** [comment]
Still not working for me :( I just getting ERROR in No NgModule metadata found for 'AppModule'. after adding "include" in tsconfig with angular 6

**Comment by hemantkumar450** [comment]
@jeroenouw  i'm still get the same issue with angular 6

**Comment by dave-ramirez** [comment]
@Zefearr @hemantkumar450 This was the solution for me, they would have to modify the file **tsconfig.app.json** and you have to see something like that

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "include": [
  "../node_modules/api-ai-javascript/*.ts",
  "../node_modules/api-ai-javascript/**/*.ts",
  "main.ts",
  "polyfills.ts"
  ],
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../node_modules/api-ai-javascript/ts/Request/TTSRequest.ts"
  ]
}

**Comment by hemantkumar450** [comment]
my **tsconfig.app.json** code
`{
  "extends": "../tsconfig.json",
  "include": [
    "../node_modules/api-ai-javascript/*.ts",
    "../node_modules/api-ai-javascript/**/*.ts",
    "main.ts",
    "polyfills.ts"
  ],
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../node_modules/api-ai-javascript/ts/Request/TTSRequest.ts"
  ],
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  }
}`

**Comment by dave-ramirez** [comment]
The error that I see is that you are not calling the .ts files
In the **include** section you have to call all the .ts using asterisk something like ***.ts**, You have your **include** section as follows:
```
"include": [
"../node_modules/api-ai-javascript/.ts",
"../node_modules/api-ai-javascript/**/.ts",
"main.ts",
"polyfills.ts"
]
```
And should correct the error add the asterisk before the .ts, something like:
```
  "include": [
  "../node_modules/api-ai-javascript/*.ts",
  "../node_modules/api-ai-javascript/**/*.ts",
  "main.ts",
  "polyfills.ts"
  ]
```

let me know if it works

**Comment by hemantkumar450** [comment]
@dave-ramirez
should i add **include** array  in **ts.config.json** also?

actually i tried in both cases. i got the same error

**Comment by hemantkumar450** [comment]
As per your instruction i did the same. but no luck
> {
  "compileOnSave": false,
  "include": [
    "node_modules/api-ai-javascript/*.ts",
    "node_modules/api-ai-javascript/**/*.ts"
  ],
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

**Comment by hemantkumar450** [comment]
@dave-ramirez
![image](https://user-images.githubusercontent.com/38126340/42637296-6f00e618-8608-11e8-945a-87fd36691c36.png)

**Comment by hemantkumar450** [comment]
@dave-ramirez , @jeroenouw , @mboughaba here's my package.JSON

> {
  "name": "chatbot",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.5",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "core-js": "^2.5.7",
    "rxjs": "^6.2.1",
    "rxjs-compat": "^6.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "api-ai-javascript": "^2.0.0-beta.21",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "^2.7.2"
  }
}`

**tsconfig.app.json**
`
{
  "extends": "../tsconfig.json",
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "../node_modules/api-ai-javascript/*.ts",
    "../node_modules/api-ai-javascript/**/*.ts",
    "main.ts",
    "polyfills.ts"
  ],
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  } 
}`



but i got the same error **ERROR in No NgModule metadata found for 'AppModule'.**

please help me out. Thanks in advance.

**Comment by ravitejagunty** [comment]
@hemantkumar450  can you post you AppModule file

**Comment by manojjayaraman** [comment]
@hemantkumar450 try using the --aot while building the app. It worked for me with the changes in place

**Comment by aravindvakil** [comment]
If you are using Angular 6.
Step 1 : In the service file import ApiAiClient from api-ai-javascript/es6/ApiAiClient

`import { ApiAiClient } from 'api-ai-javascript/es6/ApiAiClient';
`

Step 2: Then open tsconfig.json and bypass the index.ts file.

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
   "paths": {
      "api-ai-javascript/*": ["node_modules/api-ai-javascript/es6/ApiAiClient"] //bypass the index.ts
    }
  }
}
```

**Comment by vikram06** [comment]
For temporary solution to this, I have added the following check in your tsconfig.json file

  "compilerOptions": {
    "skipLibCheck": true
  }

**Comment by comicflix-tech** [comment]
ERROR in ./node_modules/angular4-carousel/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: E:\Slider\single\node_modules\angular4-carousel\index.ts is missing from the TypeScript compilation. Please make sure it
is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (E:\Slider\single\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (E:\Slider\single\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by comicflix-tech** [comment]
![image](https://user-images.githubusercontent.com/22422039/51020982-2b7ede80-15a6-11e9-9840-a19af144faf2.png)

**Comment by valeriapontillo92** [comment]
> 
> 
> @comicflix-tech I have the same issue, did you find any solutions?

open cmd as administrator.

**Comment by GBAPRO1** [comment]
To fix the "ERROR in No NgModule metadata found for 'AppModule'." you need to revert the change you did to tsconfig.app.json!

Should be this.
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

and Change the tsconfig.json to 
{
  "compileOnSave": false,
  "compilerOptions": {
    "skipLibCheck": true,
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "api-ai-javascript/*": ["node_modules/api-ai-javascript/es6/ApiAiClient"] //bypass the index.ts
      }
  }
}

ADDING paths bit and skipLibCheck

:)

**Comment by jobintweets** [comment]
> The fix from @mboughaba was not working for me. I was still gettings errors, so I changed some more in the `src/tsconfig.app.json` file (I'm using Angular 6), this was the old situation:
> 
> ```json
> {
>   "extends": "../tsconfig.json",
>   "compilerOptions": {
>     "outDir": "../out-tsc/app",
>     "module": "es2015",
>     "types": [],
>     "forceConsistentCasingInFileNames": false
>   },
>   "include": [
>     "main.ts",
>     "polyfills.ts"
>   ],
>   "exclude": [
>     "src/test.ts",
>     "**/*.spec.ts"
>   ]
> }
> ```
> 
> New situation which fixed my errors:
> 
> ```json
> {
>   "extends": "../tsconfig.json",
>   "compilerOptions": {
>     "outDir": "../out-tsc/app",
>     "module": "es2015",
>     "types": [],
>     "forceConsistentCasingInFileNames": false
>   },
>   "include": [
>     "../node_modules/api-ai-javascript/*.ts",
>     "../node_modules/api-ai-javascript/**/*.ts",
>     "main.ts",
>     "polyfills.ts"
>   ],
>   "exclude": [
>     "src/test.ts",
>     "**/*.spec.ts",
>     "../node_modules/api-ai-javascript/ts/Request/TTSRequest.ts"
>   ]
> }
> ```
> 
> I have included all the typescript files and excluded the `TTSRequest.ts` file(this was not used in the library, commented out).

thank you so much

**Comment by ghost** [comment]
getting this error :

`Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: E:\BItBucket_Local Repo\Backend\viral\CarCareAng(04Feb)\src\app\views\module\dashBoardReport\dashBoardReport.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (E:\BItBucket_Local Repo\Backend\viral\CarCareAng(04Feb)\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:767:23)
    at plugin.done.then (E:\BItBucket_Local Repo\Backend\viral\CarCareAng(04Feb)\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

also made changes into tsconfig.app.json

Not able to find the solutions

**Comment by adhivenkatesh** [comment]
Hi, i am using Angular7 but  , the files i have included in tsconfig.json bust still i am getting the error, please help get out of this , i have tried many removed ng_modules and copied to new directory but still it is ..,thanks in advance.
==========================================

ERROR in ./node_modules/rxjs/src/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\AngularProjects\AngularRouting\Routing\node_modules\rxjs\src\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\AngularProjects\AngularRouting\Routing\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (D:\AngularProjects\AngularRouting\Routing\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by adhivenkatesh** [comment]
I am using angular 7 version : the error when using ng build --aot
in that directory the files are available   but the file in that directory , i have tried removing ng_modules directory , then npm  install , nothing happened , 

**please you can see here all the configuration json files

ANY ONE CAN HELP ME HERE i have give detaily**


==========================================

**ERROR in error TS6053: File 'D:/AngularProjects/AngularRouting/Routing/src/node_modules/rxjs/src/index.ts' not found.**

TSCONFIG.JSON 

 "include": [
      "./node_modules/rxjs/src/index.ts",
     "./src/main.ts",
    // "./src/polyfills.ts",
    // "./src/**/*",
   // "./node_modules/abp-ng2-module/src/**/*"
],
"exclude": [
 "test.ts",
  "**/*.spec.ts",
  "/node_modules/routing/**/*.spec.ts"
],
"files": [
   "./node_modules/rxjs/src/index.ts"
]

------
TSCONFIG.APP.JSON
 "files": [
     "../src/app/app.module.ts",
     "./node_modules/rxjs/src/index.ts",
    //  ,
    //   "/node_modules/routing/**/*.spec.ts"
    //  ,
    //   "/node_modules/**/*.ts"
     
  ],
  "include": [
    "./node_modules/routing/**/*.spec.ts",
    "./node_modules/@ngtools/webpack/src/index.js",
    "./node_modules/rxjs/src/index.ts",
    "main.ts",
    "polyfills.ts",
  //   "./node_modules/api-ai-javascript/*.ts",
  // "./node_modules/api-ai-javascript/**/*.ts",
  "./Routing/src/main.ts"
  ]---

TSCONFIG.SPEC.JSON
"files": [
    "test.ts",
    "polyfills.ts",
    "node_modules/rxjs/src/index.ts"

  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts",
     "./node_modules/rxjs/src/index.ts",
    "./src/main.ts"
  ]

**Comment by garg10may** [comment]
I added main.ts and polyfills.ts in include in tsconfig.app.json and it compiled successfully. But the question is why it suddenly started failing was working fine until yesterday. 
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "main.ts",
    "polyfills.ts"
  ]
}
```

**Comment by prasun-git76** [comment]
i am facing this error

File C:\Users\Prasun\AppData\Roaming\npm\tsc.ps1 cannot be loaded because running 
scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1

please guide

**Comment by prasun-git76** [comment]
Hi,
After tsc compilation . js file was created with out any content

**Comment by GratiYasmine** [comment]
Please can you help me, thank you

Failed to compile.

./src/app/create-account/create-account.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: ENOENT: no such file or directory, open 'C:\Users\LENOVO\projet-leader\src\app\create-account\create-account.component.ts'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Storage.provideSync (C:\Users\LENOVO\projet-leader\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync (C:\Users\LENOVO\projet-leader\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:289:32)
    at Observable._subscribe (C:\Users\LENOVO\projet-leader\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable._trySubscribe (C:\Users\LENOVO\projet-leader\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Users\LENOVO\projet-leader\node_modules\@ngtools\webpack\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (C:\Users\LENOVO\projet-leader\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (C:\Users\LENOVO\projet-leader\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (C:\Users\LENOVO\projet-leader\node_modules\@ngtools\webpack\src\compiler_host.js:165:44)
    at VirtualFileSystemDecorator.readFile (C:\Users\LENOVO\projet-leader\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:42:54)
    at processResource (C:\Users\LENOVO\projet-leader\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (C:\Users\LENOVO\projet-leader\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at iteratePitchingLoaders (C:\Users\LENOVO\projet-leader\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\LENOVO\projet-leader\node_modules\loader-runner\lib\LoaderRunner.js:176:18
    at loadLoader (C:\Users\LENOVO\projet-leader\node_modules\loader-runner\lib\loadLoader.js:47:3)

**Comment by Tesouro74** [comment]
estou com esse erro. O que eu faço?


Failed to compile.

./src/app/top-bar/top-bar.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Lucas\Desktop\Angular\TesouroStore\src\app\top-bar\top-bar.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Lucas\Desktop\Angular\TesouroStore\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
    at C:\Users\Lucas\Desktop\Angular\TesouroStore\node_modules\@ngtools\webpack\src\loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by adhivenkatesh** [comment]
> estou com esse erro. O que eu faço?
> 
> Failed to compile.
> 
> ./src/app/top-bar/top-bar.component.ts
> Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
> Error: C:\Users\Lucas\Desktop\Angular\TesouroStore\src\app\top-bar\top-bar.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> at AngularCompilerPlugin.getCompiledFile (C:\Users\Lucas\Desktop\Angular\TesouroStore\node_modules@ngtools\webpack\src\angular_compiler_plugin.js:933:23)
> at C:\Users\Lucas\Desktop\Angular\TesouroStore\node_modules@ngtools\webpack\src\loader.js:41:31
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)

Hi From the error , i have understood the "top-bar.component.ts" file path was wrong i feel 
you can search and correct.

Thank you.

**Comment by adhivenkatesh** [comment]
Hi From the error , i have understood the "top-bar.component.ts" file path was wrong i feel
you can search and correct.

Thank you.

**Comment by chamodKanishka** [comment]
I've try all solutions to my work but it still shows error.


`Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\Chathuranga\Desktop\Projects\Created Apps\Angular\ECommerce\bookstore-frontend\src\app\models\user.ts is missing from the TypeScript compilation. Please make sure it
is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Chathuranga\Desktop\Projects\Created Apps\Angular\ECommerce\bookstore-frontend\node_modules\@ngtools\webpack\src\angular_compil
er_plugin.js:933:23)
    at plugin.done.then (C:\Users\Chathuranga\Desktop\Projects\Created Apps\Angular\ECommerce\bookstore-frontend\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by exeptionerror** [comment]
Here Is All Possible Solution added at one place [TypeError: angularCompiler.getResourceDependencies(…) is not a function or its return value is not iterable](https://exerror.com/typeerror-angularcompiler-getresourcedependencies-is-not-a-function-or-its-return-value-is-not-iterable/)

**Comment by vtassios** [comment]
I got the same error: 
```
Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error:  is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at \node_modules\@ngtools\webpack\src\ivy\loader.js:59:26
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:429:9)
```
I have 
"@angular-devkit/build-angular": "~12.2.7",
"@angular/cli": "~12.2.7",
